import os
os.system('pip install pipwin')
os.system('pipwin install pyaudio')
os.system('pip install -Iv pyttsx3==2.6 -U')
os.system('pip install speechRecognition')
os.system('pip install --user --upgrade ezgmail')
os.system('pip install wikipedia')
os.system('pip install geocoder')
os.system('pipwin install python-dateutil')
os.system('pip install wolframalpha')
os.system('pip install beautifulsoup4')
os.system('pip install requests')
